app = "agora-relay-eu"
primary_region = "ams"

[build]

[env]
  PEER_RELAYS = "wss://agora-relay.fly.dev"

[http_service]
  internal_port = 9800
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "agora_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
